server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
          route:
            RouteDefinitionLocator: INFO

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes[0]:
        id: users-service
        uri: lb://users-service
        predicates[0]: Path=/user/**
      routes[1]:
        id: orders-service
        uri: lb://orders-service
        predicates[0]: Path=/order/**
      routes[2]:
        id: products-service
        uri: lb://products-service
        predicates[0]: Path=/**
      routes[3]:
        id: discovery-service
        uri: http://localhost:8761
        predicates[0]: Path=/eureka/web
        filters[0]: SetPath=/
      routes[4]:
        id: discovery-service-static
        uri: http://localhost:8761
        predicates[0]: Path=/eureka/**
